### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by raiguard** [raiguard/Factorio-RecipeBook#1]
There is a lot of work to be done before this mod is ready.

- [x] Respect `show hidden` setting on all listboxes
- [x] List player in the recipe made-in section
- [x] Show actual craft times in recipe made-in section
- [x] Remove extraneous label in material pane, rename `as_ingredient` and `as_product` to `ingredient_in` and `product_of`, respectively
- [x] Remote interface for opening info panes
- [x] Drop an item on the RB button to view its material page
- [x] Change default hotkey to not conflict with Factory Planner
- [x] Recipe quick reference GUI
- [x] Thumbnail, mod button icon
- [x] Mod settings
- [x] Close all open GUIs in on_configuration_changed
- [x] Preserve search GUI category and listbox position when going back to it

**Upcoming**
- [ ] Rate limiting and non-essential searching smarts for search screen
- [ ] Informational tooltips (also cached in global for better runtime performance) _[REQUIRES MOD API ADDITIONS]_

**Extra Credit**
- [ ] Sorting options for info listboxes
- [ ] Preserve listbox scroll positions on info screens when navigating to them with the nav buttons
- [ ] Add indicator to last-used listbox entry when going back to an info screen with the nav buttons

**Comment by Slayman** [comment]
User input:
- [ ] color unavailable recipes differently
- [ ] PopUp Recipe window when hovering a recipe before clicking

I like the GUI very much, however especially for say pyanodon, not being able to tell if I can actually make the thing with the recipe i selected is forcing me ot use either FNEI or WIIRUF
either a 3rd pane instead of a new window for selecting a recipe or a mouseover window would help.
I don't know if I stated clearly what I want, but at least the first part is of immeasurable importance if one plays modded.

**Comment by raiguard** [comment]
Coloring unavailable recipes is on the plan for the near future.

Being able to have a "pop-up window" needs some API additions before I could do it. So that's a "maybe".

Thanks for your feedback!

**Comment by raiguard** [comment]
@Slayman So there are a few ways to go about this. Each recipe has potentially several technologies that can unlock it. WIIRUF determines which technology to show by pure luck - it just takes the first one it finds and uses that.

So there are two options: do it WIIRUF-style and just show one technology selected because we found it first, or show all technologies that can unlock it in the tooltip. Which one would be better?

Also, would it be beneficial to have this feature on materials and crafters as well, not just recipes?

**Comment by Slayman** [comment]
Ok I'm not well versed in Factorio modding. But from the way the game itself presents it to me any recipe is locked by one specific technology. Say Engines are locked behind engines even if engines is locked behind another technology.
And the one tech which specifically unlocks the tech should be the one RecipeBook shows its user.
a real Pyanodon example:
WIIRUF and FNEI hit the tech that unlocks with 100% accuracy so far:
![2020-02-20 14_25_53-Factorio 0 18 8](https://user-images.githubusercontent.com/4071149/74937965-6f6d2580-53ed-11ea-9a32-c42b7c355b5b.png)
![2020-02-20 14_26_46-Factorio 0 18 8](https://user-images.githubusercontent.com/4071149/74937983-7431d980-53ed-11ea-8722-1011405c3dc1.png)
![image](https://user-images.githubusercontent.com/4071149/74938053-988db600-53ed-11ea-9d36-9f0eeccb6894.png)

**Comment by raiguard** [comment]
Thanks for the feedback, and sorry for the huge response delay, I've been busy and preoccupied recently.

I'm going to be looking at adding information tooltips to the listboxes, but this will require a mod API addition before it will be possible. I'm also going to be significantly optimizing the search loop which will allow me to add more features to it, like results sorting, filtering, and unavailable object coloring, among other things.

I'm going to be starting on all of this after I finish LTN Manager. That mod is my main priority at the moment because people keep asking when it will be out.
